<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [4]:
%%sql

SELECT
  orderdate,
  quantity,
  netprice,
  CASE
    WHEN quantity >= 2 AND netprice >= 100 THEN 'Multiple High Value Items'
    WHEN netprice >= 100 THEN 'Single High Value Item'
    WHEN quantity >= 2 THEN 'Multiple Standard Items'
    ELSE 'Standard Order'
  END AS order_type
FROM sales
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97             Standard Order
1  2015-01-01         1    659.78     Single High Value Item
2  2015-01-01         2     54.38    Multiple Standard Items
3  2015-01-01         4    286.69  Multiple High Value Items
4  2015-01-01         7    135.75  Multiple High Value Items
5  2015-01-01         3    434.30  Multiple High Value Items
6  2015-01-01         1     58.73             Standard Order
7  2015-01-01         3     74.99    Multiple Standard Items
8  2015-01-01         2    113.57  Multiple High Value Items
9  2015-01-01         1    499.45     Single High Value Item

In [ ]:
%%sql
SELECT
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
FROM sales s
WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'

In [11]:
%%sql
WITH median_value AS (
  SELECT
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
  FROM sales s
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)
SELECT
  p.categoryname AS category,
  SUM(CASE
        WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
        AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
        THEN (s.quantity * s.netprice * s.exchangerate) END) AS low_net_revenue_2022,
  SUM(CASE
        WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
        AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
        THEN (s.quantity * s.netprice * s.exchangerate) END) AS high_net_revenue_2022,
  SUM(CASE
        WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
        AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
        THEN (s.quantity * s.netprice * s.exchangerate) END) AS low_net_revenue_2023,
  SUM(CASE
        WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
        AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
        THEN (s.quantity * s.netprice * s.exchangerate) END) AS high_net_revenue_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey,
median_value mv
GROUP BY p.categoryname
ORDER BY p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

In [20]:
%%sql
WITH percentiles AS (
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS revenue_25th_perc,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS revenue_75th_perc
  FROM sales s
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)
SELECT
  p.categoryname AS category,
  CASE
    WHEN (s.quantity * s.netprice * s.exchangerate) <= pctl.revenue_25th_perc THEN '1 - Low'
    WHEN (s.quantity * s.netprice * s.exchangerate) >= pctl.revenue_75th_perc THEN '3 - High'
    ELSE '2 - Medium'
  END AS revenue_tier,
  SUM(s.quantity * s.netprice * s.exchangerate) AS total_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey,
percentiles pctl
GROUP BY p.categoryname, revenue_tier
ORDER BY p.categoryname, revenue_tier;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio      1 - Low      267217.01
1                           Audio   2 - Medium     3832415.38
2                           Audio     3 - High     1213265.71
3         Cameras and camcorders       1 - Low       81032.92
4         Cameras and camcorders    2 - Medium     3388546.10
5         Cameras and camcorders      3 - High    15050781.63
6                     Cell phones      1 - Low      410309.35
7                     Cell phones   2 - Medium    10338963.22
8                     Cell phones     3 - High    21874993.15
9                       Computers      1 - Low      203207.06
10                      Computers   2 - Medium    10808054.11
11                      Computers     3 - High    79607760.89
12                 Games and Toys      1 - Low      533443.13
13                 Games and Toys   2 - Medium     1001381.91
14                 Games and Toys     3 - High      133749.09
15                Home Appliances      1 - Low      105045.60
16                Home Appliances   2 - Medium     4118724.64
17                Home Appliances     3 - High    22383475.30
18  Music, Movies and Audio Books      1 - Low      642496.71
19  Music, Movies and Audio Books   2 - Medium     6100817.99
20  Music, Movies and Audio Books     3 - High     3844996.29
21                   TV and Video      1 - Low       67221.76
22                   TV and Video   2 - Medium     3766783.30
23                   TV and Video     3 - High    16632856.33

In [23]:
%%sql
/*
Segment customers into age groups (e.g., <25, 25–44, 45+) and calculate their total sales (gross revenue).
This will help in understanding the purchasing behavior of different age groups.

Define age groups dynamically based on the provided data.

Calculate the total sales for each age group using: quantity * unitprice * exchangerate
*/

SELECT
  CASE
    WHEN c.age < 25 THEN '< 25'
    WHEN c.age BETWEEN 25 AND 44 THEN '25 - 44'
    ELSE '45+'
  END AS age_group,
  SUM(s.quantity * s.unitprice * s.exchangerate) AS gross_revenue
FROM sales s
JOIN customer c ON s.customerkey = c.customerkey
GROUP BY age_group;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

  age_group  gross_revenue
0      < 25    20064900.81
1   25 - 44    66490537.88
2       45+   132963615.62

In [33]:
%%sql
/*
Classify customers based on their total spending (net revenue) in 2023 into three categories: Low Spender, Medium Spender, and High Spender.
This will help in understanding the spending behavior of customers.

Define spending categories as: Low Spender (< $500), Medium Spender ($500-$2000), and High Spender (> $2000).
Use CASE WHEN to categorize customers based on their total spending.
*/

SELECT
  c.customerkey,
  SUM(s.quantity * s.netprice * s.exchangerate) AS total_spending,
  CASE
    WHEN SUM(s.quantity * s.netprice * s.exchangerate) < 500 THEN 'Low Spender'
    WHEN SUM(s.quantity * s.netprice * s.exchangerate) BETWEEN 500 AND 2000 THEN 'Medium Spender'
    ELSE 'High Spender'
  END AS spending_category
FROM sales s
JOIN customer c ON s.customerkey = c.customerkey
WHERE EXTRACT(YEAR FROM s.orderdate) = 2023
GROUP BY c.customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

13746 rows affected.

       customerkey  total_spending spending_category
0              180         1984.90    Medium Spender
1              387         1019.74    Medium Spender
2              545         3551.47      High Spender
3              649         1749.11    Medium Spender
4              688        16909.04      High Spender
...            ...             ...               ...
13741      2099174          299.00       Low Spender
13742      2099336          358.88       Low Spender
13743      2099511         2856.02      High Spender
13744      2099656         8328.22      High Spender
13745      2099743          598.46    Medium Spender

[13746 rows x 3 columns]

In [38]:
%%sql
/*
Classify products into weight categories based on their weight and weightunit from the product table.
This will help in understanding the distribution of products by weight.

  Define weight categories as follows:
  '1 - No Weight Specified' for products with no weight or weight unit specified.
  '2 - Very Light (< 5 lbs)' for products weighing less than 5 pounds.
  '3 - Light (5-25 lbs)' for products weighing between 5 and 25 pounds.
  '4 - Medium (25-100 lbs)' for products weighing between 25 and 100 pounds.
  '5 - Heavy (> 100 lbs)' for products weighing more than 100 pounds.
  '6 - Light Ounces (< 5 oz)' for products weighing less than 5 ounces.
  '7 - Heavy Ounces (≥ 5 oz)' for products weighing 5 ounces or more.
  '8 - Metric Weights' for products with weight in grams.
  '9 - Other Weight Categories' for any other weight specifications.
  Count the number of products in each weight category.
*/

SELECT
  CASE
    WHEN weightunit IS NULL OR weight IS NULL THEN '1 - No Weight Specified'
    WHEN weightunit = 'pounds' AND weight < 5 THEN '2 - Very Light (< 5 lbs)'
    WHEN weightunit = 'pounds' AND weight >= 5 AND weight < 25 THEN '3 - Light (5-25 lbs)'
    WHEN weightunit = 'pounds' AND weight >= 25 AND weight <= 100 THEN '4 - Medium (25-100 lbs)'
    WHEN weightunit = 'pounds' AND weight > 100 THEN '5 - Heavy (> 100 lbs)'
    WHEN weightunit = 'ounces' AND weight < 5 THEN '6 - Light Ounces (< 5 oz)'
    WHEN weightunit = 'ounces' AND weight >= 5 THEN '7 - Heavy Ounces (≥ 5 oz)'
    WHEN weightunit = 'grams' THEN '8 - Metric Weights'
    ELSE '9 - Other Weight Categories'
END AS weight_category,
COUNT(productkey) AS total_products
FROM product
GROUP BY weight_category
ORDER BY weight_category

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

             weight_category  total_products
0    1 - No Weight Specified             284
1   2 - Very Light (< 5 lbs)             568
2       3 - Light (5-25 lbs)             728
3    4 - Medium (25-100 lbs)             414
4      5 - Heavy (> 100 lbs)             112
5  6 - Light Ounces (< 5 oz)             225
6  7 - Heavy Ounces (≥ 5 oz)             176
7         8 - Metric Weights              10

In [35]:
%%sql
/*
Classify stores based on squaremeters and net revenue to analyze their contribution in 2023:

Calculate Revenue by Store and Size

Use a Common Table Expression (CTE) to compute total revenue for each store based on sales data, while also getting it's store size.

Categorize Stores

Assign each store to a category based on its squaremeters and net revenue:
1 - Small Store - Low Revenue: < 1000 sqm, revenue < 100,000
2 - Small Store - High Revenue: < 1000 sqm, revenue ≥ 100,000
3 - Medium Store - Low Revenue: 1000-2000 sqm, revenue < 300,000
4 - Medium Store - High Revenue: 1000-2000 sqm, revenue ≥ 300,000
5 - Large Store - Low Revenue: > 2000 sqm, revenue < 500,000
6 - Large Store - High Revenue: > 2000 sqm, revenue ≥ 500,000
7 - Online Store: Any stores that do not fit the above criteria. (i.e., squaremeters IS NULL)
Analyze Revenue Contribution

Compute net revenue per category.
Determine percentage contribution of each category to overall revenue.
Order by the store categorization.
*/
WITH store_revenue AS (
  SELECT
    storekey,
    SUM(s.quantity * s.netprice * s.exchangerate) AS revenue
  FROM store
  GROUP BY storekey
)
SELECT
  CASE
    WHEN st.squaremeters IS NULL THEN '7 - Online Store'
    WHEN st.squaremeters < 1000 AND sr.revenue < 100000 THEN '1 - Small Store - Low Revenue'
    WHEN st.squaremeters < 1000 AND sr.revenue >= 100000 THEN '2 - Small Store - High Revenue'
    WHEN st.squaremeters >= 1000 AND st.squaremeters <= 2000 AND sr.revenue < 300000 THEN '3 - Medium Store - Low Revenue'
    WHEN st.squaremeters >= 1000 AND st.squaremeters <= 2000 AND sr.revenue >= 300000 THEN '4 - Medium Store - High Revenue'
    WHEN st.squaremeters > 2000 AND sr.revenue < 500000 THEN '5 - Large Store - Low Revenue'
    WHEN st.squaremeters > 2000 AND sr.revenue >= 500000 THEN '6 - Large Store - High Revenue'
    ELSE '7 - Online Store'
END AS store_category
FROM sales s
JOIN store st ON s.storekey = st.storekey
JOIN store_revenue sr ON sr.storekey = st.storekey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

  weightunit
0       None
1     pounds
2     ounces
3      grams