<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [108]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [111]:
%%sql

SELECT
  CURRENT_DATE,
  orderdate
FROM sales
WHERE orderdate >= CURRENT_DATE - INTERVAL '5 years'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

106750 rows affected.

       current_date   orderdate
0        2026-07-13  2021-07-13
1        2026-07-13  2021-07-13
2        2026-07-13  2021-07-13
3        2026-07-13  2021-07-13
4        2026-07-13  2021-07-13
...             ...         ...
106745   2026-07-13  2024-04-20
106746   2026-07-13  2024-04-20
106747   2026-07-13  2024-04-20
106748   2026-07-13  2024-04-20
106749   2026-07-13  2024-04-20

[106750 rows x 2 columns]

In [112]:
%%sql
SELECT
  CURRENT_DATE,
  s.orderdate,
  p. categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE orderdate >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY s.orderdate, p.categoryname
ORDER BY s.orderdate, p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

7722 rows affected.

     current_date   orderdate                   categoryname  net_revenue
0      2026-07-13  2021-07-13                          Audio       789.48
1      2026-07-13  2021-07-13        Cameras and camcorders       2427.91
2      2026-07-13  2021-07-13                    Cell phones     14576.77
3      2026-07-13  2021-07-13                      Computers     37502.03
4      2026-07-13  2021-07-13                 Games and Toys       382.25
...           ...         ...                            ...          ...
7717   2026-07-13  2024-04-20                      Computers     58353.68
7718   2026-07-13  2024-04-20                 Games and Toys      1744.30
7719   2026-07-13  2024-04-20                Home Appliances      1562.04
7720   2026-07-13  2024-04-20  Music, Movies and Audio Books      4949.43
7721   2026-07-13  2024-04-20                   TV and Video      9841.91

[7722 rows x 4 columns]

In [119]:
%%sql
SELECT EXTRACT(YEAR FROM AGE(NOW(),'2001-03-15')) AS my_age;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  my_age
0     25

In [131]:
%%sql
SELECT
  DATE_PART('year', orderdate) AS order_year,
  ROUND(AVG(EXTRACT(DAYS FROM AGE(deliverydate, orderdate))), 2) AS avg_processing_time,
  CAST(SUM(quantity * netprice * exchangerate) AS INTEGER) AS net_revenue
FROM sales
WHERE orderdate >= CURRENT_DATE - INTERVAL '6 years'
GROUP BY order_year
ORDER BY order_year;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

   order_year avg_processing_time  net_revenue
0     2020.00                1.02      2393159
1     2021.00                1.36     21357977
2     2022.00                1.62     44864557
3     2023.00                1.75     33108566
4     2024.00                1.67      8396527

In [150]:
%%sql
/*
Calculate the operational lifespan in months for each store with a 'Closed' status.
This analysis helps in understanding how long stores were in operation before they were permanently closed.

Extract the year and month from the closedate and opendate to calculate operational_lifespan_months.
*/

SELECT
  storekey,
  EXTRACT(YEAR FROM AGE(closedate, opendate)) * 12 + EXTRACT(MONTH FROM AGE(closedate, opendate)) AS month_lifespan
FROM store
WHERE closedate IS NOT NULL;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

16 rows affected.

    storekey month_lifespan
0         20            101
1         30             43
2         70             82
3         72             36
4        110             71
5        200             79
6        250             63
7        280             55
8        350             97
9        410             63
10       460             30
11       465             49
12       520             72
13       580             95
14       600            104
15       630            139

In [156]:
%%sql

/*
Analyze the age of customers by calculating their age in months and days, and categorizing them into age groups. This final table will help in understanding the demographic distribution of the customer base.

Extract the year and month from the birthday to calculate the age in months.
Use the AGE function to calculate the age in days from CURRENT_DATE.
Categorize customers into age groups:
'Under 25'
'25-50'
'50+'.
*/

SELECT
  customerkey,
  EXTRACT(YEAR FROM AGE(CURRENT_DATE, birthday)) * 12 + EXTRACT(MONTH FROM AGE(CURRENT_DATE, birthday))
FROM customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

104990 rows affected.

        customerkey ?column?
0                15      735
1                23      434
2                36      743
3               120      955
4               180      854
...             ...      ...
104985      2099639      974
104986      2099656      970
104987      2099697      715
104988      2099711     1026
104989      2099743      316

[104990 rows x 2 columns]