<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [78]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [79]:
%%sql

SELECT
  DATE_PART('year', orderdate) AS order_year,
  DATE_PART('month', orderdate) AS order_month,
  DATE_PART('day', orderdate) AS order_day
FROM sales
ORDER BY RANDOM()
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   order_year  order_month  order_day
0     2016.00         6.00      10.00
1     2023.00         2.00      25.00
2     2021.00        10.00      21.00
3     2018.00        10.00      15.00
4     2022.00         7.00       1.00
5     2022.00         7.00      14.00
6     2018.00         6.00      30.00
7     2017.00         1.00      10.00
8     2018.00         5.00       2.00
9     2023.00         8.00      31.00

In [82]:
%%sql
SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(MONTH FROM orderdate) AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
GROUP BY order_year, order_month
ORDER BY order_year;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue
0         2015           1    384092.66
1         2015           2    706374.12
2         2015           3    332961.59
3         2015           4    160767.00
4         2015           5    548632.63
..         ...         ...          ...
107       2023          12   2928550.93
108       2024           1   2677498.55
109       2024           2   3542322.55
110       2024           3   1692854.89
111       2024           4    483851.39

[112 rows x 3 columns]

In [87]:
%%sql
SELECT
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE (EXTRACT(YEAR FROM CURRENT_DATE) -  EXTRACT(YEAR FROM orderdate)) <= 5
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

       orderdate                   categoryname  net_revenue
0     2021-01-01                          Audio      1206.67
1     2021-01-01        Cameras and camcorders       2228.75
2     2021-01-01                    Cell phones     10582.00
3     2021-01-01                      Computers     12718.95
4     2021-01-01                 Games and Toys       235.53
...          ...                            ...          ...
8952  2024-04-20                      Computers     58353.68
8953  2024-04-20                 Games and Toys      1744.30
8954  2024-04-20                Home Appliances      1562.04
8955  2024-04-20  Music, Movies and Audio Books      4949.43
8956  2024-04-20                   TV and Video      9841.91

[8957 rows x 3 columns]

In [92]:
%%sql
/*
For each order, identify the following time components: decade, quarter, month, year, and ISO year. This will help analyze the distribution of orders over time.

Use the EXTRACT function to retrieve these values from the orderdate column.
*/

SELECT
  orderkey,
  EXTRACT(DECADE FROM orderdate) order_decade,
  EXTRACT(QUARTER FROM orderdate) order_quarter,
  EXTRACT(MONTH FROM orderdate) order_month,
  EXTRACT(YEAR FROM orderdate) order_year,
  EXTRACT(ISOYEAR FROM orderdate) order_isoyear
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,order_decade,order_quarter,order_month,order_year,order_isoyear
0,1000,201,1,1,2015,2015
1,1000,201,1,1,2015,2015
2,1001,201,1,1,2015,2015
3,1002,201,1,1,2015,2015
4,1002,201,1,1,2015,2015
...,...,...,...,...,...,...
199868,3398034,202,2,4,2024,2024
199869,3398034,202,2,4,2024,2024
199870,3398035,202,2,4,2024,2024
199871,3398035,202,2,4,2024,2024
199872,3398035,202,2,4,2024,2024

In [95]:
%%sql
/*
Calculate the total net revenue for each day of the year in 2022. This will help in understanding the daily revenue trends for that year.

Use DATE_PART to extract the day of the year from orderdate.
Calculate the total net revenue for each day.
Filter for the year of 2022 using DATE_PART.
Group the results by the day of the year and order them chronologically.
*/

SELECT
  DATE_PART('doy', orderdate)::INT AS order_day,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE DATE_PART('year', orderdate) = 2022
GROUP BY order_day
ORDER BY order_day

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

365 rows affected.

     order_day  net_revenue
0            1    255185.54
1            2     30229.29
2            3    141615.78
3            4    129968.60
4            5    171813.44
..         ...          ...
360        361    113441.22
361        362    198531.19
362        363    202345.75
363        364    184191.39
364        365    231514.53

[365 rows x 2 columns]

In [105]:
%%sql
/*
Analyze sales activity by day of the week for the year five years prior to the current date.
This analysis will reveal daily sales patterns from a consistent historical timeframe relative to when the query is run. Your query should:

Dynamically filter the data to include only records from the year that was exactly 5 years before the current year.

Count the total number of order line items for each day of the week.

Group and sort the results by the day of the week.

Note: Because this query uses the current date, the specific year being analyzed will change.
The results you get will be different depending on the year you run this code.
*/

SELECT
  EXTRACT(DOW FROM orderdate) AS order_day_of_week,
  COUNT(orderkey) AS total_orders
FROM sales
WHERE (EXTRACT(YEAR FROM CURRENT_DATE) -  EXTRACT(YEAR FROM orderdate)) = 5
GROUP BY order_day_of_week
ORDER BY order_day_of_week;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

7 rows affected.

  order_day_of_week  total_orders
0                 0           377
1                 1          2089
2                 2          2640
3                 3          3501
4                 4          3888
5                 5          2720
6                 6          4570

In [107]:
%%sql
/*
Analyze the distribution of orders over the last 6 years by extracting specific date components from the orderdate in the sales table. This will help in understanding the order trends over time.

Extract the year and quarter from the orderdate in separate columns.
For each of these columns of year and quarter, you must calculate two specific metrics:

The total number of order line items.

The total number of unique customers.

Filter the data to include only orders from the last 6 years from the current date using DATE_PART() and NOW().
Group the results by year and quarter, and order them chronologically.
*/

SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(QUARTER FROM orderdate) AS order_quarter,
  COUNT(orderkey) AS total_orders,
  COUNT(DISTINCT customerkey) AS unique_customers
FROM sales
WHERE DATE_PART('year', NOW()) - DATE_PART('year', orderdate) <= 6
GROUP BY order_year, order_quarter
ORDER BY order_year, order_quarter;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

18 rows affected.

   order_year order_quarter  total_orders  unique_customers
0        2020             1          6054              2542
1        2020             2          2434              1033
2        2020             3          1471               612
3        2020             4          1308               566
4        2021             1          2173               906
5        2021             2          3559              1466
6        2021             3          5597              2336
7        2021             4          8456              3396
8        2022             1         10566              4248
9        2022             2          9972              4002
10       2022             3         12267              4799
11       2022             4         12946              5142
12       2023             1         11267              4485
13       2023             2          7794              3164
14       2023             3          8744              3509
15       2023             4          9712              3853
16       2024             1          9534              3867
17       2024             2           597               246

In [96]:
%%sql
select * from sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38