<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [40]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [49]:
%%sql

SELECT
  DATE_TRUNC('month', orderdate)::DATE AS ordermonth,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM sales
GROUP BY ordermonth;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

     ordermonth  net_revenue  total_unique_customers
0    2015-01-01    384092.66                     200
1    2015-02-01    706374.12                     291
2    2015-03-01    332961.59                     139
3    2015-04-01    160767.00                      78
4    2015-05-01    548632.63                     236
..          ...          ...                     ...
107  2023-12-01   2928550.93                    1484
108  2024-01-01   2677498.55                    1340
109  2024-02-01   3542322.55                    1718
110  2024-03-01   1692854.89                     877
111  2024-04-01    483851.39                     246

[112 rows x 3 columns]

In [53]:
%%sql

SELECT
  orderdate,
  TO_CHAR(orderdate, 'YYYY-MM') AS year_month
FROM sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate year_month
0       2015-01-01    2015-01
1       2015-01-01    2015-01
2       2015-01-01    2015-01
3       2015-01-01    2015-01
4       2015-01-01    2015-01
...            ...        ...
199868  2024-04-20    2024-04
199869  2024-04-20    2024-04
199870  2024-04-20    2024-04
199871  2024-04-20    2024-04
199872  2024-04-20    2024-04

[199873 rows x 2 columns]

In [55]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS ordermonth,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM sales
GROUP BY ordermonth;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    ordermonth  net_revenue  total_unique_customers
0      2015-01    384092.66                     200
1      2015-02    706374.12                     291
2      2015-03    332961.59                     139
3      2015-04    160767.00                      78
4      2015-05    548632.63                     236
..         ...          ...                     ...
107    2023-12   2928550.93                    1484
108    2024-01   2677498.55                    1340
109    2024-02   3542322.55                    1718
110    2024-03   1692854.89                     877
111    2024-04    483851.39                     246

[112 rows x 3 columns]

In [74]:
%%sql
/*
Calculate the total quantity of products sold each quarter from the sales table.
Use DATE_TRUNC to group the sales data by quarter and order the results by quarter.
*/

SELECT
  DATE_TRUNC('year', orderdate)::DATE AS quarter,
  SUM(quantity) AS products_sold
FROM sales
GROUP BY DATE_TRUNC('year', orderdate)
ORDER BY quarter;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

      quarter  products_sold
0  2015-01-01          21591
1  2016-01-01          26869
2  2017-01-01          33903
3  2018-01-01          69587
4  2019-01-01          85066
5  2020-01-01          35234
6  2021-01-01          62108
7  2022-01-01         143836
8  2023-01-01         118173
9  2024-01-01          32003

In [66]:
%%sql
/*
Calculate the total net revenue sold each week in 2023 from the sales table.
Use TO_CHAR to group the sales data by week and use TO_CHAR to filter for the year '2023'.
*/
SELECT
  TO_CHAR(orderdate, 'WW-YYYY') AS week,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY TO_CHAR(orderdate, 'WW-YYYY')
ORDER BY TO_CHAR(orderdate, 'WW-YYYY');

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

53 rows affected.

       week  net_revenue
0   01-2023   1118860.15
1   02-2023    773467.25
2   03-2023    797088.74
3   04-2023    782617.25
4   05-2023    717966.27
5   06-2023    736953.05
6   07-2023   1306411.98
7   08-2023   1565117.98
8   09-2023    855867.58
9   10-2023    674366.67
10  11-2023    572372.82
11  12-2023    296270.32
12  13-2023    192971.20
13  14-2023    136913.60
14  15-2023    155401.94
15  16-2023    319794.80
16  17-2023    521159.07
17  18-2023    753761.03
18  19-2023    593732.21
19  20-2023    640474.39
20  21-2023    680621.01
21  22-2023    656573.65
22  23-2023    639532.20
23  24-2023    691279.78
24  25-2023    651605.62
25  26-2023    630744.45
26  27-2023    663660.52
27  28-2023    578634.87
28  29-2023    594352.59
29  30-2023    344437.15
30  31-2023    330799.10
31  32-2023    596693.03
32  33-2023    707979.33
33  34-2023    638344.63
34  35-2023    621132.00
35  36-2023    623176.05
36  37-2023    651658.91
37  38-2023    525843.34
38  39-2023    589952.09
39  40-2023    620493.42
40  41-2023    656365.04
41  42-2023    520907.25
42  43-2023    569826.74
43  44-2023    574432.72
44  45-2023    632663.06
45  46-2023    664647.45
46  47-2023    627628.45
47  48-2023    594660.28
48  49-2023    613843.74
49  50-2023    622248.89
50  51-2023    759557.47
51  52-2023    717107.77
52  53-2023      5594.66

In [77]:
%%sql
/*
Calculate the median quantity of products sold each week in 2023 from the sales table.
Use DATE_TRUNC to group the sales data by week and use DATE_TRUNC to filter for the year 2023.
*/

SELECT
  DATE_TRUNC('week', orderdate)::DATE AS week,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY quantity) AS products_sold_median
FROM sales
WHERE DATE_TRUNC('year', orderdate)::DATE = '2023-01-01'
GROUP BY DATE_TRUNC('week', orderdate)
ORDER BY DATE_TRUNC('week', orderdate);

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

53 rows affected.

          week  products_sold_median
0   2022-12-26                  3.00
1   2023-01-02                  3.00
2   2023-01-09                  2.00
3   2023-01-16                  3.00
4   2023-01-23                  3.00
5   2023-01-30                  2.00
6   2023-02-06                  3.00
7   2023-02-13                  2.00
8   2023-02-20                  3.00
9   2023-02-27                  2.00
10  2023-03-06                  2.00
11  2023-03-13                  2.00
12  2023-03-20                  3.00
13  2023-03-27                  2.00
14  2023-04-03                  3.00
15  2023-04-10                  3.00
16  2023-04-17                  2.00
17  2023-04-24                  2.00
18  2023-05-01                  3.00
19  2023-05-08                  2.00
20  2023-05-15                  3.00
21  2023-05-22                  2.00
22  2023-05-29                  2.00
23  2023-06-05                  2.00
24  2023-06-12                  3.00
25  2023-06-19                  3.00
26  2023-06-26                  3.00
27  2023-07-03                  2.00
28  2023-07-10                  2.00
29  2023-07-17                  2.00
30  2023-07-24                  2.50
31  2023-07-31                  3.00
32  2023-08-07                  2.00
33  2023-08-14                  3.00
34  2023-08-21                  3.00
35  2023-08-28                  3.00
36  2023-09-04                  2.00
37  2023-09-11                  2.00
38  2023-09-18                  2.00
39  2023-09-25                  2.00
40  2023-10-02                  2.00
41  2023-10-09                  3.00
42  2023-10-16                  2.00
43  2023-10-23                  2.00
44  2023-10-30                  3.00
45  2023-11-06                  2.00
46  2023-11-13                  3.00
47  2023-11-20                  2.00
48  2023-11-27                  3.00
49  2023-12-04                  3.00
50  2023-12-11                  3.00
51  2023-12-18                  2.00
52  2023-12-25                  2.00