<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [12]:
%%sql
/*
Find the table that lists currencies and their associated exchange rates based on a date. Then perform a query to find all unique currencies that are used in the dataset.
*/

SELECT DISTINCT fromcurrency AS currency
FROM currencyexchange
UNION
SELECT DISTINCT fromcurrency AS currency
FROM currencyexchange;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

  currency
0      CAD
1      EUR
2      AUD
3      USD
4      GBP

In [3]:
%%sql

/*
Find the table that contains product information such as category and price. Then perform a query to find the most expensive price for a given category.
*/
SELECT
  categoryname,
  MAX(price)
FROM product
GROUP BY categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname     max
0                          Audio  299.23
1                Home Appliances 3199.99
2  Music, Movies and Audio Books  289.99
3                   TV and Video 2899.99
4                 Games and Toys  598.80
5                    Cell phones  589.00
6                      Computers 2499.00
7        Cameras and camcorders  1620.00

In [10]:
%%sql
/*
Find the total number of orders made in stores located in each country. You'll need to explore the database to find the relevant tables that contain both order details and store information.
*/
SELECT
  st.countryname,
  COUNT(DISTINCT sa.orderkey) AS total_orders
FROM store st
LEFT JOIN sales sa ON st.storekey = sa.storekey
GROUP BY st.countryname
ORDER BY 2 DESC;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

9 rows affected.

      countryname  total_orders
0          Online         32482
1   United States         26488
2  United Kingdom          5674
3          Canada          5230
4         Germany          5224
5       Australia          2862
6     Netherlands          2066
7           Italy          1640
8          France          1464

In [7]:
%%sql
select * from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [ ]:
s