<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [44]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [47]:
%%sql

SELECT
  p. categoryname AS category,
  SUM(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s. quantity * s.netprice * s.exchangerate) END) AS total_revenue_2022,
  SUM(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS total_revenue_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p. categoryname
ORDER BY p. categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  total_revenue_2022  total_revenue_2023
0                          Audio           766938.21           688690.18
1        Cameras and camcorders           2382532.56          1983546.29
2                    Cell phones          8119665.07          6002147.63
3                      Computers         17862213.49         11650867.21
4                 Games and Toys           316127.30           270374.96
5                Home Appliances          6612446.68          5919992.87
6  Music, Movies and Audio Books          2989297.28          2180768.13
7                   TV and Video          5815336.61          4412178.23

In [49]:
%%sql
SELECT
  p. categoryname AS category,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s. quantity * s.netprice * s.exchangerate) END) AS min_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s. quantity * s.netprice * s.exchangerate) END) AS avg_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s. quantity * s.netprice * s.exchangerate) END) AS max_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_revenue_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p. categoryname
ORDER BY p. categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,min_revenue_2022,avg_revenue_2022,max_revenue_2022,avg_revenue_2023
0,Audio,9.31,392.30,3473.36,425.38
1,Cameras and camcorders,6.74,1210.02,15008.39,1210.96
2,Cell phones,2.53,722.20,7692.37,623.28
3,Computers,0.83,1565.62,38082.66,1292.39
4,Games and Toys,2.83,81.29,5202.01,80.83
5,Home Appliances,4.04,1755.36,31654.55,1886.55
6,"Music, Movies and Audio Books",7.29,386.61,5415.19,334.58
7,TV and Video,41.30,1535.61,30259.41,1687.90

In [52]:
%%sql
SELECT
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY netprice) AS median_price
FROM sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [56]:
%%sql
SELECT
  p. categoryname AS category,
  PERCENTILE_CONT(0.5) WITHIN GROUP (
    ORDER BY
      CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s. quantity * s.netprice * s.exchangerate) END
  ) AS median_sales_2022,
  PERCENTILE_CONT(0.5) WITHIN GROUP (
    ORDER BY
      CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s. quantity * s.netprice * s.exchangerate) END
  ) AS median_sales_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p. categoryname
ORDER BY p. categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  median_sales_2022  median_sales_2023
0                          Audio             257.21             266.59
1        Cameras and camcorders              651.46             672.60
2                    Cell phones             418.60             375.88
3                      Computers             809.70             657.18
4                 Games and Toys              33.78              32.62
5                Home Appliances             791.00             825.25
6  Music, Movies and Audio Books             186.58             159.63
7                   TV and Video             730.46             790.79

In [63]:
%%sql
/*
Determine the average, minimum, and maximum net revenue for each continent for the year 2022.
This will help in understanding the revenue performance across different continents.

Use AVG, MIN, and MAX to calculate the respective statistics for each continent.
*/

SELECT
  c.continent,
  MIN(s. quantity * s.netprice * s.exchangerate) AS min_revenue_2022,
  AVG(s. quantity * s.netprice * s.exchangerate) AS avg_revenue_2022,
  MAX(s. quantity * s.netprice * s.exchangerate) AS max_revenue_2022
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY c.continent;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent  min_revenue_2022  avg_revenue_2022  max_revenue_2022
0      Australia              4.54           1336.18          24182.95
1         Europe              1.68            860.21          25725.87
2  North America              0.83            999.22          38082.66

In [65]:
%%sql
/*
Calculate the average net revenue generated by each categoryname for small, medium, and large stores.
This will help in understanding the revenue contribution from different store sizes.

Define store sizes as: small (<1000 square meters), medium (1000-2000 square meters), and large (>2000 square meters).
Group the results by categoryname to aggregate the revenue per category.
*/

SELECT
  p.categoryname,
  AVG(CASE WHEN st.squaremeters < 1000 THEN s.quantity * s.netprice * s.exchangerate END) AS avg_small_store_revenue,
  AVG(CASE WHEN st.squaremeters BETWEEN 1000 AND 2000 THEN s.quantity * s.netprice * s.exchangerate END) AS avg_medium_store_revenue,
  AVG(CASE WHEN st.squaremeters > 2000 THEN s.quantity * s.netprice * s.exchangerate END) AS avg_large_store_revenue
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
LEFT JOIN store st ON s.storekey = st.storekey
GROUP BY p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_small_store_revenue,avg_medium_store_revenue,avg_large_store_revenue
0,Audio,329.00,336.86,347.52
1,Cameras and camcorders,1392.44,1391.82,1600.37
2,Cell phones,778.91,821.71,853.67
3,Computers,1974.16,2119.08,2259.95
4,Games and Toys,83.72,82.48,84.00
5,Home Appliances,1390.73,1522.02,1522.81
6,"Music, Movies and Audio Books",301.18,318.26,332.62
7,TV and Video,1479.13,1412.76,1532.97

In [76]:
%%sql
/*
Determine the maximum net revenue generated by each country for each quarter in 2023.
This will help in understanding the highest revenue performance across countries for specific periods.

Use MAX with CASE WHEN to calculate the net revenue for each date range.
Define date ranges as: Q1 (January to March), Q2 (April to June), Q3 (July to September), and Q4 (October to December).
Group the results by country.
*/

SELECT
  c.countryfull,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-03-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_revenue_Q1,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-04-01' AND '2023-06-30'THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_revenue_Q2,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-07-01' AND '2023-09-30' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_revenue_Q3,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-10-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_revenue_Q4
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
GROUP BY c.countryfull;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,countryfull,max_revenue_q1,max_revenue_q2,max_revenue_q3,max_revenue_q4
0,Australia,15402.31,16019.39,16719.22,29075.44
1,Canada,25424.67,28264.64,27611.60,32915.59
2,France,15375.42,14358.10,13546.29,9365.31
3,Germany,25772.22,19249.54,17350.34,14751.06
4,Italy,13170.85,11000.96,12268.68,7821.64
5,Netherlands,18137.03,15350.72,11888.10,17540.68
6,United Kingdom,15582.22,18072.26,19456.28,17403.32
7,United States,23868.00,26679.91,25087.92,20655.00

In [78]:
%%sql
/*
Calculate the median net revenue for different age groups across various countries.
This will help in understanding the spending patterns of different age demographics.

Define age groups as: Young (< 30), Middle-aged (30-50), and Senior (> 50).
Group the results by countryname from the store table to see the median revenue for each age group in each country.
*/

SELECT
  st.countryname,
  PERCENTILE_CONT(0.5) WITHIN GROUP (
    ORDER BY
      CASE WHEN c.age < 30 THEN (s. quantity * s.netprice * s.exchangerate) END
  ) AS median_revenue_young_customers,
  PERCENTILE_CONT(0.5) WITHIN GROUP (
    ORDER BY
      CASE WHEN c.age BETWEEN 30 AND 50 THEN (s. quantity * s.netprice * s.exchangerate) END
  ) AS median_revenue_middle_aged_customers,
  PERCENTILE_CONT(0.5) WITHIN GROUP (
    ORDER BY
      CASE WHEN c.age > 50 THEN (s. quantity * s.netprice * s.exchangerate) END
  ) AS median_revenue_senior_customers
FROM sales s
LEFT JOIN store st ON s.storekey = st.storekey
LEFT JOIN customer c ON c.customerkey = s.customerkey
GROUP BY st.countryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

9 rows affected.

,countryname,median_revenue_young_customers,median_revenue_middle_aged_customers,median_revenue_senior_customers
0,Australia,589.32,556.49,608.88
1,Canada,515.31,560.68,530.06
2,France,332.01,367.02,377.58
3,Germany,342.64,363.95,344.88
4,Italy,395.01,343.75,343.18
5,Netherlands,344.43,392.51,344.05
6,Online,399.99,392.38,399.84
7,United Kingdom,309.04,296.78,317.01
8,United States,404.62,404.97,400.49