<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [ ]:
%%sql

SELECT
  customerkey,
  orderkey,
  linenumber,
  (quantity * netprice * exchangerate) AS net_revenue,
  AVG(quantity * netprice * exchangerate) OVER() AS avg_net_revenue_all_orders
FROM sales
ORDER BY customerkey
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey  orderkey  linenumber  net_revenue  avg_net_revenue_all_orders
0           15   2259001           0      2217.41                     1032.69
1          180   3162018           0        71.36                     1032.69
2          180   1305016           0       525.31                     1032.69
3          180   3162018           1      1913.55                     1032.69
4          185   1613010           0      1395.52                     1032.69
5          243    505008           0       287.67                     1032.69
6          387   2495044           0      1265.56                     1032.69
7          387   1451007           1       619.77                     1032.69
8          387   1451007           0      1608.10                     1032.69
9          387   1451007           2        97.05                     1032.69

In [ ]:
%%sql

SELECT
  customerkey,
  orderkey,
  linenumber,
  (quantity * netprice * exchangerate) AS net_revenue,
  AVG(quantity * netprice * exchangerate) OVER(PARTITION BY customerkey) AS avg_net_revenue_this_cstmr
FROM sales
ORDER BY customerkey
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey  orderkey  linenumber  net_revenue  avg_net_revenue_this_cstmr
0           15   2259001           0      2217.41                     2217.41
1          180   1305016           0       525.31                      836.74
2          180   3162018           1      1913.55                      836.74
3          180   3162018           0        71.36                      836.74
4          185   1613010           0      1395.52                     1395.52
5          243    505008           0       287.67                      287.67
6          387   3242015           2       180.35                      517.32
7          387   3242015           1       362.44                      517.32
8          387   3242015           0        30.51                      517.32
9          387   3242015           3       446.44                      517.32

In [ ]:
%%sql

SELECT
  orderdate,
  orderkey * 10 + linenumber AS order_line_number,
  (quantity * netprice * exchangerate) AS net_revenue,
  SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS daily_net_revenue,
  (quantity * netprice * exchangerate) * 100 / SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS pct_daily_revenue
FROM sales
ORDER BY
  orderdate,
  pct_daily_revenue DESC
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
5,2015-01-01,10021,950.25,11640.80,8.16
6,2015-01-01,10041,578.52,11640.80,4.97
7,2015-01-01,10081,574.05,11640.80,4.93
8,2015-01-01,10001,423.28,11640.80,3.64
9,2015-01-01,10040,263.11,11640.80,2.26

In [ ]:
%%sql

SELECT *,
  (net_revenue * 100) / daily_net_revenue AS pct_daily_revenue
FROM
  (SELECT
    orderdate,
    orderkey * 10 + linenumber AS order_line_number,
    (quantity * netprice * exchangerate) AS net_revenue,
    SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS daily_net_revenue
  FROM sales) AS revenue_by_day
ORDER BY orderdate, pct_daily_revenue DESC;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
...,...,...,...,...,...
199868,2024-04-20,33980141,12.00,96879.43,0.01
199869,2024-04-20,33980074,9.29,96879.43,0.01
199870,2024-04-20,33980080,8.35,96879.43,0.01
199871,2024-04-20,33980142,8.34,96879.43,0.01
199872,2024-04-20,33980310,6.89,96879.43,0.01

In [ ]:
%%sql

WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year
  FROM sales
  ORDER BY customerkey
)
SELECT
  yc.cohort_year,
  EXTRACT(YEAR FROM s.orderdate) AS purchase_year,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN yearly_cohort yc ON s.customerkey = yc.customerkey
GROUP BY
  yc.cohort_year,
  purchase_year;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  net_revenue
0         2015          2015   7370979.48
1         2015          2016    392623.48
2         2015          2017    479841.31
3         2015          2018   1069850.87
4         2015          2019   1235991.48
5         2015          2020    386489.60
6         2015          2021    872845.99
7         2015          2022   1569787.72
8         2015          2023   1157633.91
9         2015          2024    356186.62
10        2016          2016   9990990.20
11        2016          2017    497028.11
12        2016          2018   1074607.29
13        2016          2019   1565400.72
14        2016          2020    474087.09
15        2016          2021    964417.85
16        2016          2022   2164681.10
17        2016          2023   1265242.63
18        2016          2024    364066.76
19        2017          2017  12244469.63
20        2017          2018   1407065.13
21        2017          2019   1764716.90
22        2017          2020    625928.03
23        2017          2021   1329858.72
24        2017          2022   2428882.80
25        2017          2023   1714010.18
26        2017          2024    464802.56
27        2018          2018  21115924.55
28        2018          2019   3229188.22
29        2018          2020   1171126.65
30        2018          2021   2201262.39
31        2018          2022   4534295.81
32        2018          2023   3271753.92
33        2018          2024    936833.89
34        2019          2019  24022798.65
35        2019          2020   1295044.99
36        2019          2021   2337594.77
37        2019          2022   4848980.74
38        2019          2023   3440099.20
39        2019          2024    751725.53
40        2020          2020   7265759.44
41        2020          2021   1016399.07
42        2020          2022   1891708.40
43        2020          2023   1435051.04
44        2020          2024    312983.02
45        2021          2021  12635597.87
46        2021          2022   3014082.50
47        2021          2023   2242369.63
48        2021          2024    495686.18
49        2022          2022  24412138.13
50        2022          2023   4237220.04
51        2022          2024   1223450.12
52        2023          2023  14345184.96
53        2023          2024    634143.37
54        2024          2024   2856649.33

In [ ]:
%%sql
/*
Analyze the distribution of product quantities ordered by each customer across different stores.
This will help in understanding customer purchasing behavior at various store locations.

Select the customerkey, storekey, and quantity from the sales table.
Use a window function to calculate the total quantity of products ordered per store.
Use another window function to calculate the total quantity of products ordered by each customer at each store.
Order the results by storekey and customerkey.
*/

SELECT
  customerkey,
  storekey,
  quantity,
  SUM(quantity) OVER(PARTITION BY storekey) AS store_products_ordered,
  SUM(quantity) OVER(PARTITION BY customerkey, storekey) AS customer_store_products_ordered
FROM sales
ORDER BY storekey, customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,storekey,quantity,store_products_ordered,customer_store_products_ordered
0,545,10,4,2395,29
1,545,10,7,2395,29
2,545,10,3,2395,29
3,545,10,6,2395,29
4,545,10,8,2395,29
...,...,...,...,...,...
199868,2099656,999999,1,246072,12
199869,2099697,999999,1,246072,5
199870,2099697,999999,3,246072,5
199871,2099697,999999,1,246072,5
199872,2099711,999999,1,246072,1

In [ ]:
%%sql
/*
Calculate the average quantity of products ordered for each customer and compare it to the overall average quantity of products ordered across all customers.
This will help in understanding individual customer ordering behavior relative to the overall trend.

Select the customerkey, orderkey, linenumber, and quantity from the sales table.
Use a window function to calculate the overall average quantity of products ordered.
Use another window function to calculate the average quantity of products ordered by each customer.
Order the results by customerkey.
*/

SELECT
  customerkey,
  orderkey,
  linenumber,
  quantity,
  ROUND(AVG(quantity) OVER(), 2) AS avg_products_ordered,
  AVG(quantity) OVER(PARTITION BY customerkey) AS avg_products_ordered_by_customer
FROM sales
ORDER BY customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderkey,linenumber,quantity,avg_products_ordered,avg_products_ordered_by_customer
0,15,2259001,0,5,3.14,5.0000000000000000
1,180,1305016,0,1,3.14,2.0000000000000000
2,180,3162018,0,2,3.14,2.0000000000000000
3,180,3162018,1,3,3.14,2.0000000000000000
4,185,1613010,0,3,3.14,3.0000000000000000
...,...,...,...,...,...,...
199868,2099711,957007,0,6,3.14,3.5000000000000000
199869,2099711,591007,0,1,3.14,3.5000000000000000
199870,2099743,2633018,1,1,3.14,3.0000000000000000
199871,2099743,2633018,0,6,3.14,3.0000000000000000
199872,2099743,2964016,0,2,3.14,3.0000000000000000

In [ ]:
%%sql
/*
Calculate the weekly revenue for the year 2023 and analyze how each week's revenue compares to the average weekly revenue.
This will help in understanding the revenue trends throughout the year.

Extract the week number from the orderdate.
Calculate the total revenue for each week in 2023.
Determine the average weekly revenue for the year.
Calculate the percentage of each week's revenue relative to the average weekly revenue.
Order the results by week number.
*/

WITH weekly_data AS (
  SELECT
  EXTRACT(WEEK FROM orderdate) AS week_num,
  SUM(quantity * netprice * exchangerate) AS total_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY week_num
)
SELECT
  week_num,
  total_revenue,
  AVG(total_revenue) OVER() AS avg_revenue,
  total_revenue / AVG(total_revenue) OVER() * 100 AS pct_of_avg
FROM weekly_data
ORDER BY week_num;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

52 rows affected.

   week_num  total_revenue  avg_revenue  pct_of_avg
0         1     1101256.97    636703.18      172.96
1         2      779868.87    636703.18      122.49
2         3      785218.52    636703.18      123.33
3         4      803262.51    636703.18      126.16
4         5      703916.98    636703.18      110.56
5         6      743952.80    636703.18      116.84
6         7     1326232.87    636703.18      208.30
7         8     1574117.57    636703.18      247.23
8         9      834392.35    636703.18      131.05
9        10      675247.13    636703.18      106.05
10       11      556619.96    636703.18       87.42
11       12      292027.79    636703.18       45.87
12       13      184214.94    636703.18       28.93
13       14      136774.78    636703.18       21.48
14       15      158549.96    636703.18       24.90
15       16      322698.71    636703.18       50.68
16       17      528255.09    636703.18       82.97
17       18      751256.50    636703.18      117.99
18       19      590863.67    636703.18       92.80
19       20      642957.46    636703.18      100.98
20       21      673644.04    636703.18      105.80
21       22      667780.72    636703.18      104.88
22       23      631210.02    636703.18       99.14
23       24      697356.78    636703.18      109.53
24       25      655077.94    636703.18      102.89
25       26      630134.72    636703.18       98.97
26       27      672726.64    636703.18      105.66
27       28      560633.11    636703.18       88.05
28       29      593552.79    636703.18       93.22
29       30      346776.19    636703.18       54.46
30       31      328282.67    636703.18       51.56
31       32      608504.70    636703.18       95.57
32       33      698802.09    636703.18      109.75
33       34      653199.04    636703.18      102.59
34       35      612023.53    636703.18       96.12
35       36      617106.03    636703.18       96.92
36       37      651458.74    636703.18      102.32
37       38      527992.88    636703.18       82.93
38       39      599748.17    636703.18       94.20
39       40      636804.20    636703.18      100.02
40       41      631069.97    636703.18       99.12
41       42      518406.38    636703.18       81.42
42       43      592495.16    636703.18       93.06
43       44      567162.11    636703.18       89.08
44       45      642432.29    636703.18      100.90
45       46      673092.66    636703.18      105.72
46       47      606362.83    636703.18       95.23
47       48      588515.73    636703.18       92.43
48       49      615839.18    636703.18       96.72
49       50      620651.43    636703.18       97.48
50       51      760170.78    636703.18      119.39
51       52      737866.57    636703.18      115.89

In [2]:
%%sql
/*
Perform a cohort analysis to understand how revenue accumulates over time for different customer groups,
where each cohort is defined by the year of their first purchase.

First, assign each customer a cohort year using the year of their first order.
Then, calculate the monthly revenue per cohort by summing all transactions within each cohort-month.
Use a window function to calculate the cumulative revenue for each cohort over time.
Also calculate each month’s revenue as a percentage of the cohort's total revenue.
Finally, order the results by cohort_year and order_month to observe revenue growth over time.

Use EXTRACT(YEAR FROM MIN(orderdate)) OVER (PARTITION BY customerkey) to determine each customer's cohort year.
Use quantity * netprice * exchangerate to calculate the revenue per transaction.
Use DATE_TRUNC('month', orderdate) to group revenue by month.
Use SUM(...) OVER (PARTITION BY cohort_year ORDER BY order_month) for cumulative revenue.
Use monthly_revenue / SUM(...) OVER (PARTITION BY cohort_year) to get each month’s revenue as a percent of cohort total.
*/

WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year,
    DATE_TRUNC('month', orderdate) order_month
  FROM sales
  ORDER BY customerkey, cohort_year, order_month
)
SELECT
  yc.*,
  SUM(quantity * netprice * exchangerate) AS  net_revenue,
  SUM(quantity * netprice * exchangerate) OVER(PARTITION BY cohort_year ORDER BY order_month) AS cumulative_revenue,
  net_revenue / SUM(net_revenue) OVER(PARTITION BY cohort_year) AS pct_of_total
FROM sales s
LEFT JOIN yearly_cohort yc ON s.customerkey = yc.customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

RuntimeError: (The named parameters feature is "disabled". Enable it with: %config SqlMagic.named_parameters="enabled".
For more info, see the docs: https://jupysql.ploomber.io/en/latest/api/configuration.html#named-parameters)
(psycopg2.errors.WindowingError) window functions are not allowed in GROUP BY
LINE 4:     EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY custo...
                              ^

[SQL: WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year,
    DATE_TRUNC('month', orderdate) order_month,
    SUM(quantity * netprice * exchangerate) AS  net_revenue
  FROM sales
  GROUP BY customerkey, cohort_year, order_month
  ORDER BY customerkey, cohort_year, order_month
)
SELECT
  yc.*,
  SUM(net_revenue) OVER(PARTITION BY cohort_year ORDER BY order_month) AS cumulative_revenue,
  net_revenue / SUM(net_revenue) OVER(PARTITION BY cohort_year) AS pct_of_total
FROM sales s
LEFT JOIN yearly_cohort yc ON s.customerkey = yc.customerkey;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [10]:
%%sql
/*
Perform a cohort analysis to understand how revenue accumulates over time for different customer groups,
where each cohort is defined by the year of their first purchase.

First, assign each customer a cohort year using the year of their first order.
Then, calculate the monthly revenue per cohort by summing all transactions within each cohort-month.
Use a window function to calculate the cumulative revenue for each cohort over time.
Also calculate each month’s revenue as a percentage of the cohort's total revenue.
Finally, order the results by cohort_year and order_month to observe revenue growth over time.

Use EXTRACT(YEAR FROM MIN(orderdate)) OVER (PARTITION BY customerkey) to determine each customer's cohort year.
Use quantity * netprice * exchangerate to calculate the revenue per transaction.
Use DATE_TRUNC('month', orderdate) to group revenue by month.
Use SUM(...) OVER (PARTITION BY cohort_year ORDER BY order_month) for cumulative revenue.
Use monthly_revenue / SUM(...) OVER (PARTITION BY cohort_year) to get each month’s revenue as a percent of cohort total.
*/
WITH cohort_sales AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year,
    DATE_TRUNC('month', orderdate) order_month,
    quantity * netprice * exchangerate AS revenue
  FROM sales
),
monthly_revenue AS (
  SELECT
    cohort_year,
    order_month,
    SUM(revenue) AS monthly_revenue
  FROM cohort_sales
  GROUP BY cohort_year, order_month
)
SELECT
  cohort_year,
  TO_CHAR(order_month, 'YYYY-MM') AS order_month,
  monthly_revenue,
  SUM(monthly_revenue) OVER(PARTITION BY cohort_year ORDER BY order_month) AS cumulative_revenue,
  monthly_revenue / SUM(monthly_revenue) OVER(PARTITION BY cohort_year) * 100 pct_of_total
FROM monthly_revenue
ORDER BY
    cohort_year,
    order_month;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

580 rows affected.

    cohort_year order_month  monthly_revenue  cumulative_revenue  pct_of_total
0          2015     2015-01        383950.23           383950.23          2.58
1          2015     2015-02        706374.12          1090324.36          4.74
2          2015     2015-03        332961.59          1423285.95          2.24
3          2015     2015-04        160767.00          1584052.94          1.08
4          2015     2015-05        548632.63          2132685.58          3.68
..          ...         ...              ...                 ...           ...
575        2023     2024-04         59557.16         14975560.96          0.40
576        2024     2024-01        870007.11           870007.11         30.46
577        2024     2024-02       1277239.17          2147246.29         44.71
578        2024     2024-03        565740.73          2712987.02         19.80
579        2024     2024-04        143646.69          2856633.71          5.03

[580 rows x 5 columns]