<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [9]:
%%sql

WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  FIRST_VALUE(net_revenue) OVER(ORDER BY month) AS first_month_revenue,
  LAST_VALUE(net_revenue) OVER(ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_month_revenue,
  NTH_VALUE(net_revenue, 6) OVER(ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS sixth_month_revenue
FROM monthly_revenue;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,first_month_revenue,last_month_revenue,sixth_month_revenue
0,2023-01,3664431.34,3664431.34,2928550.93,2864500.03
1,2023-02,4465204.57,3664431.34,2928550.93,2864500.03
2,2023-03,2244316.52,3664431.34,2928550.93,2864500.03
3,2023-04,1162796.16,3664431.34,2928550.93,2864500.03
4,2023-05,2943005.99,3664431.34,2928550.93,2864500.03
5,2023-06,2864500.03,3664431.34,2928550.93,2864500.03
6,2023-07,2337639.34,3664431.34,2928550.93,2864500.03
7,2023-08,2623919.79,3664431.34,2928550.93,2864500.03
8,2023-09,2622774.85,3664431.34,2928550.93,2864500.03
9,2023-10,2551322.61,3664431.34,2928550.93,2864500.03
10,2023-11,2700103.38,3664431.34,2928550.93,2864500.03
11,2023-12,2928550.93,3664431.34,2928550.93,2864500.03

In [10]:
%%sql

WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  LAG(net_revenue) OVER(ORDER BY month) AS previous_month_revenue,
  LEAD(net_revenue) OVER(ORDER BY month) AS next_month_revenue
FROM monthly_revenue;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  previous_month_revenue
0   2023-01   3664431.34                     NaN
1   2023-02   4465204.57              3664431.34
2   2023-03   2244316.52              4465204.57
3   2023-04   1162796.16              2244316.52
4   2023-05   2943005.99              1162796.16
5   2023-06   2864500.03              2943005.99
6   2023-07   2337639.34              2864500.03
7   2023-08   2623919.79              2337639.34
8   2023-09   2622774.85              2623919.79
9   2023-10   2551322.61              2622774.85
10  2023-11   2700103.38              2551322.61
11  2023-12   2928550.93              2700103.38

In [13]:
%%sql

WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  LAG(net_revenue) OVER(ORDER BY month) AS previous_month_revenue,
  (net_revenue - LAG(net_revenue) OVER(ORDER BY month)) / LAG(net_revenue) OVER(ORDER BY month) * 100 AS monthly_revenue_growth
FROM monthly_revenue;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  previous_month_revenue  monthly_revenue_growth
0   2023-01   3664431.34                     NaN                     NaN
1   2023-02   4465204.57              3664431.34                   21.85
2   2023-03   2244316.52              4465204.57                  -49.74
3   2023-04   1162796.16              2244316.52                  -48.19
4   2023-05   2943005.99              1162796.16                  153.10
5   2023-06   2864500.03              2943005.99                   -2.67
6   2023-07   2337639.34              2864500.03                  -18.39
7   2023-08   2623919.79              2337639.34                   12.25
8   2023-09   2622774.85              2623919.79                   -0.04
9   2023-10   2551322.61              2622774.85                   -2.72
10  2023-11   2700103.38              2551322.61                    5.83
11  2023-12   2928550.93              2700103.38                    8.46

In [17]:
%%sql
WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
    SUM(quantity * netprice * exchangerate) AS customer_ltv
  FROM sales
  GROUP BY customerkey
),
cohort_summary AS (
  SELECT
    cohort_year,
    customerkey,
    customer_ltv,
    AVG(customer_ltv) OVER (PARTITION BY cohort_year) AS avg_cohort_ltv
  FROM yearly_cohort
  ORDER BY
    cohort_year,
    customerkey
),
cohort_final AS (
  SELECT DISTINCT
    cohort_year,
    avg_cohort_ltv
  FROM cohort_summary
  ORDER BY cohort_year
)
SELECT
  *,
  LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year) AS prev_cohort_ltv,
  (avg_cohort_ltv -  LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year)) /  LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year) AS ltv_change
FROM cohort_final;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year  avg_cohort_ltv  prev_cohort_ltv  ltv_change
0        2015         5271.59              NaN         NaN
1        2016         5404.92          5271.59        0.03
2        2017         5403.08          5404.92       -0.00
3        2018         4896.64          5403.08       -0.09
4        2019         4731.95          4896.64       -0.03
5        2020         3933.32          4731.95       -0.17
6        2021         3943.33          3933.32        0.00
7        2022         3315.52          3943.33       -0.16
8        2023         2543.18          3315.52       -0.23
9        2024         2037.55          2543.18       -0.20

In [23]:
%%sql
/*
Analyze weekly order trends for the year 2023 and compare each week’s performance to other key weeks. This helps identify patterns and fluctuations in weekly activity.

Use a CTE to aggregate the total number of distinct orders for each week in 2023.
In the final query, use window functions to compare each week’s total orders to:
The first week’s total
The third week’s total
The previous week
The next week
*/

WITH distinct_orders AS (
  SELECT
    DATE_TRUNC('week', orderdate) AS orderweek,
    COUNT(DISTINCT orderkey) AS unique_orders
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY orderweek
  ORDER BY orderweek
)
SELECT
  orderweek,
  unique_orders,
  FIRST_VALUE(unique_orders) OVER(ORDER BY orderweek) AS first_week_orders,
  NTH_VALUE(unique_orders, 3) OVER(ORDER BY orderweek ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS third_week_orders,
  LAG(unique_orders) OVER(ORDER BY orderweek) AS prev_week_orders,
  LEAD(unique_orders) OVER(ORDER BY orderweek) AS next_week_orders
FROM distinct_orders;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

53 rows affected.

,orderweek,unique_orders,first_week_orders,third_week_orders,prev_week_orders,next_week_orders
0,2022-12-26 00:00:00+00:00,12,12,363,NaN,444.00
1,2023-01-02 00:00:00+00:00,444,12,363,12.00,363.00
2,2023-01-09 00:00:00+00:00,363,12,363,444.00,343.00
3,2023-01-16 00:00:00+00:00,343,12,363,363.00,348.00
4,2023-01-23 00:00:00+00:00,348,12,363,343.00,346.00
5,2023-01-30 00:00:00+00:00,346,12,363,348.00,352.00
6,2023-02-06 00:00:00+00:00,352,12,363,346.00,607.00
7,2023-02-13 00:00:00+00:00,607,12,363,352.00,642.00
8,2023-02-20 00:00:00+00:00,642,12,363,607.00,373.00
9,2023-02-27 00:00:00+00:00,373,12,363,642.00,326.00
10,2023-03-06 00:00:00+00:00,326,12,363,373.00,264.00
11,2023-03-13 00:00:00+00:00,264,12,363,326.00,159.00
12,2023-03-20 00:00:00+00:00,159,12,363,264.00,83.00
13,2023-03-27 00:00:00+00:00,83,12,363,159.00,57.00
14,2023-04-03 00:00:00+00:00,57,12,363,83.00,83.00
15,2023-04-10 00:00:00+00:00,83,12,363,57.00,149.00
16,2023-04-17 00:00:00+00:00,149,12,363,83.00,250.00
17,2023-04-24 00:00:00+00:00,250,12,363,149.00,322.00
18,2023-05-01 00:00:00+00:00,322,12,363,250.00,310.00
19,2023-05-08 00:00:00+00:00,310,12,363,322.00,306.00
20,2023-05-15 00:00:00+00:00,306,12,363,310.00,314.00
21,2023-05-22 00:00:00+00:00,314,12,363,306.00,307.00
22,2023-05-29 00:00:00+00:00,307,12,363,314.00,301.00
23,2023-06-05 00:00:00+00:00,301,12,363,307.00,307.00
24,2023-06-12 00:00:00+00:00,307,12,363,301.00,305.00
25,2023-06-19 00:00:00+00:00,305,12,363,307.00,297.00
26,2023-06-26 00:00:00+00:00,297,12,363,305.00,304.00
27,2023-07-03 00:00:00+00:00,304,12,363,297.00,299.00
28,2023-07-10 00:00:00+00:00,299,12,363,304.00,278.00
29,2023-07-17 00:00:00+00:00,278,12,363,299.00,166.00
30,2023-07-24 00:00:00+00:00,166,12,363,278.00,175.00
31,2023-07-31 00:00:00+00:00,175,12,363,166.00,282.00
32,2023-08-07 00:00:00+00:00,282,12,363,175.00,295.00
33,2023-08-14 00:00:00+00:00,295,12,363,282.00,297.00
34,2023-08-21 00:00:00+00:00,297,12,363,295.00,286.00
35,2023-08-28 00:00:00+00:00,286,12,363,297.00,294.00
36,2023-09-04 00:00:00+00:00,294,12,363,286.00,296.00
37,2023-09-11 00:00:00+00:00,296,12,363,294.00,285.00
38,2023-09-18 00:00:00+00:00,285,12,363,296.00,289.00
39,2023-09-25 00:00:00+00:00,289,12,363,285.00,289.00
40,2023-10-02 00:00:00+00:00,289,12,363,289.00,287.00
41,2023-10-09 00:00:00+00:00,287,12,363,289.00,288.00
42,2023-10-16 00:00:00+00:00,288,12,363,287.00,289.00
43,2023-10-23 00:00:00+00:00,289,12,363,288.00,291.00
44,2023-10-30 00:00:00+00:00,291,12,363,289.00,288.00
45,2023-11-06 00:00:00+00:00,288,12,363,291.00,291.00
46,2023-11-13 00:00:00+00:00,291,12,363,288.00,289.00
47,2023-11-20 00:00:00+00:00,289,12,363,291.00,288.00
48,2023-11-27 00:00:00+00:00,288,12,363,289.00,290.00
49,2023-12-04 00:00:00+00:00,290,12,363,288.00,319.00
50,2023-12-11 00:00:00+00:00,319,12,363,290.00,376.00
51,2023-12-18 00:00:00+00:00,376,12,363,319.00,402.00
52,2023-12-25 00:00:00+00:00,402,12,363,376.00,NaN

In [44]:
%%sql
/*
Analyze how each customer’s order revenue changes over time by comparing each order to their first, second, previous, and next orders.
This helps track spending patterns and behavioral shifts at the individual level.

Use a CTE to calculate the total revenue per order by grouping on customerkey, orderkey, and orderdate.
In the main query, use window functions to capture:
The first order amount
The second order amount
The previous order amount
The next order amount
This enables side-by-side comparison of a customer’s current order with their ordering history.
*/

WITH customer_orders AS (
  SELECT
    customerkey,
    orderkey,
    orderdate,
    SUM(quantity * netprice * exchangerate) AS revenue
  FROM sales
  GROUP BY customerkey, orderkey, orderdate
  ORDER BY customerkey, orderkey, orderdate
)
SELECT
  customerkey,
  orderkey,
  orderdate,
  revenue,
  FIRST_VALUE(revenue) OVER(PARTITION BY customerkey ORDER BY orderdate) AS first_order_amount,
  NTH_VALUE(revenue, 2) OVER(PARTITION BY customerkey ORDER BY orderdate) AS second_order_amount,
  LAG(revenue) OVER(PARTITION BY customerkey ORDER BY orderdate) AS prev_order_amount,
  LEAD(revenue) OVER(PARTITION BY customerkey ORDER BY orderdate) AS next_order_amount
FROM customer_orders
ORDER BY customerkey, orderkey, orderdate;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

83130 rows affected.

,customerkey,orderkey,orderdate,revenue,first_order_amount,second_order_amount,prev_order_amount,next_order_amount
0,15,2259001,2021-03-08,2217.41,2217.41,NaN,NaN,NaN
1,180,1305016,2018-07-28,525.31,525.31,NaN,NaN,1984.90
2,180,3162018,2023-08-28,1984.90,525.31,1984.90,525.31,NaN
3,185,1613010,2019-06-01,1395.52,1395.52,NaN,NaN,NaN
4,243,505008,2016-05-19,287.67,287.67,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
83125,2099697,2813044,2022-09-13,38.20,38.20,NaN,NaN,NaN
83126,2099711,591007,2016-08-13,2067.75,2067.75,NaN,NaN,3940.92
83127,2099711,957007,2017-08-14,3940.92,2067.75,3940.92,2067.75,NaN
83128,2099743,2633018,2022-03-17,469.62,469.62,NaN,NaN,598.46
83129,2099743,2964016,2023-02-11,598.46,469.62,598.46,469.62,NaN

In [47]:
%%sql
/*
Analyze how each store's total revenue has changed year over year, allowing you to identify growth or decline patterns across time.

Use a CTE to calculate the total net revenue per store per year by aggregating transactions by storekey and order_year.
In the main query, use window functions to:
Retrieve the store’s revenue for the next year
Calculate the percentage change in revenue between the current year and the next year
This helps quantify store-level performance trends over time.
*/

WITH store_revenues AS (
  SELECT
    storekey,
    EXTRACT(YEAR FROM orderdate) AS orderyear,
    SUM(quantity * netprice * exchangerate) AS revenue
  FROM sales
  GROUP BY storekey, orderyear
)
SELECT
  storekey,
  orderyear,
  revenue,
  LEAD(revenue) OVER(PARTITION BY storekey ORDER BY orderyear) AS next_year_revenue,
  (LEAD(revenue) OVER(PARTITION BY storekey ORDER BY orderyear) - revenue) / revenue * 100 AS pct_revenue_change
FROM store_revenues
ORDER BY storekey, orderyear

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

599 rows affected.

     storekey orderyear     revenue  next_year_revenue  pct_revenue_change
0          10      2015    93555.57           29455.75              -68.52
1          10      2016    29455.75           73457.07              149.38
2          10      2017    73457.07          114153.75               55.40
3          10      2018   114153.75          236707.95              107.36
4          10      2019   236707.95           75607.66              -68.06
..        ...       ...         ...                ...                 ...
594    999999      2020  2675169.93         8798749.55              228.90
595    999999      2021  8798749.55        24127533.28              174.22
596    999999      2022 24127533.28        20089790.85              -16.73
597    999999      2023 20089790.85         4871371.55              -75.75
598    999999      2024  4871371.55                NaN                 NaN

[599 rows x 5 columns]

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql