<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [7]:
%%sql

WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year,
    EXTRACT(YEAR FROM orderdate) AS purchase_year
  FROM
    sales
)
SELECT DISTINCT
  cohort_year,
  purchase_year,
  COUNT(customerkey) OVER(PARTITION BY purchase_year, cohort_year) AS total_customers
FROM yearly_cohort
ORDER BY cohort_year, purchase_year;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  total_customers
0         2015          2015             2825
1         2015          2016              126
2         2015          2017              149
3         2015          2018              348
4         2015          2019              388
5         2015          2020              171
6         2015          2021              295
7         2015          2022              600
8         2015          2023              499
9         2015          2024              146
10        2016          2016             3397
11        2016          2017              174
12        2016          2018              374
13        2016          2019              457
14        2016          2020              205
15        2016          2021              336
16        2016          2022              746
17        2016          2023              573
18        2016          2024              183
19        2017          2017             4068
20        2017          2018              473
21        2017          2019              570
22        2017          2020              251
23        2017          2021              450
24        2017          2022              943
25        2017          2023              738
26        2017          2024              246
27        2018          2018             7446
28        2018          2019             1081
29        2018          2020              475
30        2018          2021              779
31        2018          2022             1644
32        2018          2023             1407
33        2018          2024              426
34        2019          2019             7755
35        2019          2020              523
36        2019          2021              873
37        2019          2022             1700
38        2019          2023             1439
39        2019          2024              370
40        2020          2020             3031
41        2020          2021              358
42        2020          2022              694
43        2020          2023              547
44        2020          2024              163
45        2021          2021             4663
46        2021          2022             1051
47        2021          2023              889
48        2021          2024              268
49        2022          2022             9010
50        2022          2023             1764
51        2022          2024              561
52        2023          2023             5890
53        2023          2024              332
54        2024          2024             1402

In [9]:
%%sql

WITH customer_orders AS (
  SELECT
    customerkey,
    (quantity * netprice * exchangerate) AS order_value,
    COUNT(*) OVER(PARTITION BY customerkey) AS total_orders
  FROM sales
)
SELECT
  customerkey,
  total_orders,
  AVG(order_value) AS net_revenue
FROM customer_orders
GROUP BY customerkey, total_orders;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey  total_orders  net_revenue
0               15             1      2217.41
1              180             3       836.74
2              185             1      1395.52
3              243             1       287.67
4              387             9       517.32
...            ...           ...          ...
49482      2099619             8       838.74
49483      2099656            13       800.36
49484      2099697             3        12.73
49485      2099711             2      3004.34
49486      2099743             3       356.03

[49487 rows x 3 columns]

In [13]:
%%sql

WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
    SUM(quantity * netprice * exchangerate) AS customer_ltv
  FROM sales
  GROUP BY customerkey
)
SELECT
  *,
  AVG(customer_ltv) OVER(PARTITION BY cohort_year) AS avg_cohort_ltv
FROM yearly_cohort
ORDER BY cohort_year, customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  avg_cohort_ltv
0             4376        2015        182.00         5271.59
1             4403        2015       9530.35         5271.59
2             4925        2015       6078.08         5271.59
3             5729        2015        192.16         5271.59
4             6048        2015       1903.89         5271.59
...            ...         ...           ...             ...
49482      2093965        2024        475.22         2037.55
49483      2095129        2024        156.00         2037.55
49484      2095691        2024        326.00         2037.55
49485      2096470        2024        535.78         2037.55
49486      2097541        2024       1143.15         2037.55

[49487 rows x 4 columns]

In [15]:
%%sql

SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
FROM sales
WHERE orderdate >= '2020-01-01'; -- filters data before applying window function

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

        customerkey cohort_year
0                15        2021
1               180        2023
2               180        2023
3               387        2021
4               387        2021
...             ...         ...
124446      2099697        2022
124447      2099697        2022
124448      2099743        2022
124449      2099743        2022
124450      2099743        2022

[124451 rows x 2 columns]

In [16]:
%%sql

WITH cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
  FROM sales
)
SELECT *
FROM cohort
WHERE cohort_year >= 2020;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

81370 rows affected.

       customerkey cohort_year
0               15        2021
1              406        2021
2              406        2021
3              545        2023
4              545        2023
...            ...         ...
81365      2099697        2022
81366      2099697        2022
81367      2099743        2022
81368      2099743        2022
81369      2099743        2022

[81370 rows x 2 columns]

In [19]:
%%sql
/*
Analyze how much quantity each customer orders and how it compares to the average quantity ordered at both the customer level and the store level.

Select customerkey, storekey, and quantity from the sales table to view individual transactions.
Use two window functions:
One to calculate the average quantity ordered per customer
One to calculate the average quantity ordered per store
This helps you understand whether a customer tends to order more or less than the store average, and whether certain stores
have higher or lower order quantities on average.
Order the results by customerkey and storekey for easier comparison.
*/

SELECT
  customerkey,
  storekey,
  quantity,
  ROUND(AVG(quantity) OVER(PARTITION BY customerkey), 2) AS avg_quantity_per_customer,
  ROUND(AVG(quantity) OVER(PARTITION BY storekey), 2)  AS avg_quantity_per_store
FROM sales
ORDER BY customerkey, storekey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,storekey,quantity,avg_quantity_per_customer,avg_quantity_per_store
0,15,999999,5,5.00,3.14
1,180,50,2,2.00,3.15
2,180,50,3,2.00,3.15
3,180,999999,1,2.00,3.14
4,185,50,3,3.00,3.15
...,...,...,...,...,...
199868,2099711,670,6,3.50,3.19
199869,2099711,999999,1,3.50,3.14
199870,2099743,540,2,3.00,3.07
199871,2099743,610,6,3.00,3.14
199872,2099743,610,1,3.00,3.14

In [23]:
%%sql
/*
Identify how many unique orders each customer placed in 2022 to better understand purchasing frequency across the customer base.

First, use a CTE to select distinct customerkey, orderkey, and orderdate from the sales table, filtered to only include orders from 2022.
Then, use a window function to count the total number of orders per customer.
Finally, order the results by total_orders in descending order, then by customerkey to highlight the most active customers first.
This allows you to rank and compare customers based on how frequently they placed orders during the year.
*/

WITH orders_2022 AS (
  SELECT DISTINCT
    customerkey,
    orderkey,
    orderdate
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
)
SELECT
  *,
  COUNT(*) OVER(PARTITION BY customerkey) AS total_orders
FROM orders_2022
ORDER BY total_orders DESC, customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

18895 rows affected.

       customerkey  orderkey   orderdate  total_orders
0           368817   2917044  2022-12-26             5
1           368817   2700016  2022-05-23             5
2           368817   2711006  2022-06-03             5
3           368817   2822027  2022-09-22             5
4           368817   2918016  2022-12-27             5
...            ...       ...         ...           ...
18890      2099380   2824060  2022-09-24             1
18891      2099511   2822044  2022-09-22             1
18892      2099603   2631007  2022-03-15             1
18893      2099697   2813044  2022-09-13             1
18894      2099743   2633018  2022-03-17             1

[18895 rows x 4 columns]

In [28]:
%%sql
/*
Calculate the lifetime value (LTV) for each individual customer and compare it to the average LTV of other customers in the same birth decade.
This will help identify which customers—and which generations—tend to spend more over time.

Use a CTE to calculate the total revenue (LTV) for each customerkey, based on their full purchase history.
Extract the birth decade of each customer using their birthday, and include it in the aggregation.
In the main query, calculate the average LTV for each birth decade using a window function.
Filter to include only customers with LTV greater than 1000.
Order the results by birth_decade and customerkey.
*/

WITH ltv AS (
  SELECT
    c.customerkey,
    EXTRACT(DECADE FROM c.birthday) * 10 AS birth_decade,
    SUM(s.quantity * s.netprice * s.exchangerate) AS customer_ltv
  FROM sales s
  JOIN customer c ON s.customerkey = c.customerkey
  GROUP BY c.customerkey, birth_decade
)
SELECT
  *,
  AVG(customer_ltv) OVER(PARTITION BY birth_decade)
FROM ltv
WHERE customer_ltv > 1000
ORDER BY birth_decade, customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

35585 rows affected.

       customerkey birth_decade  customer_ltv     avg
0              649         1930       4063.09 5586.39
1             2268         1930       1243.54 5586.39
2             2599         1930       8608.97 5586.39
3             3706         1930       1759.19 5586.39
4             4713         1930       1993.40 5586.39
...            ...          ...           ...     ...
35580      2092434         2000       6611.90 5868.09
35581      2093202         2000       1504.75 5868.09
35582      2093263         2000       2440.68 5868.09
35583      2093736         2000       4049.01 5868.09
35584      2099743         2000       1068.08 5868.09

[35585 rows x 4 columns]

In [39]:
%%sql
/*
Calculate the total net revenue generated by each individual customer between 2015 and 2020, and compare
it to the average revenue of other customers within the same gender group.

Use a CTE (net_revenue_base) to compute net_revenue per transaction (quantity * netprice * exchangerate).
Filter the data in that CTE to only include sales from 2015 to 2020 using orderdate.
In the next CTE (customer_sales), join the net_revenue_base CTE with the customer table to attach the gender column.
This CTE needs to determine the total revenue (total_revenue) associated with each customer.
Ensure the data prepared by this CTE accurately represents each unique customer only once before proceeding to the next step.
In the final SELECT statement:
Calculate the avg_revenue_by_gender by finding the average of the total_revenue values for the unique customers within each gender group
(Hint: A window function like AVG(...) OVER (PARTITION BY gender) is suitable here, operating on the prepared data from customer_sales).
Compute a revenue_vs_group ratio (e.g., as a percentage) comparing each customer's total_revenue to their calculated avg_revenue_by_gender.
Return customerkey, gender, total_revenue, avg_revenue_by_gender, and revenue_vs_group.
*/

WITH net_revenue_base AS (
  SELECT
    customerkey,
    (quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) BETWEEn 2015 AND 2020
),
customer_sales AS (
  SELECT
    nrb.customerkey,
    c.gender,
    SUM(nrb.net_revenue) AS total_revenue
  FROM net_revenue_base nrb
  JOIN customer c ON nrb.customerkey = c.customerkey
  GROUP BY nrb.customerkey, c.gender
)
SELECT
  customerkey,
  gender,
  total_revenue,
  AVG(total_revenue) OVER(PARTITION BY gender) AS avg_revenue_by_gender,
  total_revenue * 100 /  AVG(total_revenue) OVER(PARTITION BY gender) revenue_vs_group
FROM customer_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

28522 rows affected.

,customerkey,gender,total_revenue,avg_revenue_by_gender,revenue_vs_group
0,2099711,female,6008.67,3460.79,173.62
1,185,female,1395.52,3460.79,40.32
2,243,female,287.67,3460.79,8.31
3,387,female,2370.54,3460.79,68.50
4,957,female,567.12,3460.79,16.39
...,...,...,...,...,...
28517,1657577,male,4362.60,3458.78,126.13
28518,1212224,male,4754.82,3458.78,137.47
28519,2044999,male,358.20,3458.78,10.36
28520,1990450,male,7262.05,3458.78,209.96
28521,1212351,male,3086.65,3458.78,89.24