<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT
  customerkey,
  orderdate,
  (quantity * netprice * exchangerate) AS net_revenue,
  COUNT(*) OVER(
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS running_order_count,
  AVG(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS running_avg_revenue
FROM
  sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_order_count
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,71.36,3,836.74
3,180,2023-08-28,1913.55,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
...,...,...,...,...,...
199868,2099711,2016-08-13,2067.75,1,2067.75
199869,2099711,2017-08-14,3940.92,2,3004.34
199870,2099743,2022-03-17,375.57,2,234.81
199871,2099743,2022-03-17,94.05,2,234.81
199872,2099743,2023-02-11,598.46,3,356.03

In [10]:
%%sql

WITH row_nums AS(
  SELECT
    ROW_NUMBER() OVER(
      PARTITION BY orderdate
      ORDER BY orderdate, orderkey, linenumber
    ) AS row_num,
    *
  FROM sales
)
SELECT *
FROM row_nums
WHERE orderdate > '2015-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
1,2,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
2,3,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
3,4,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
4,5,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
5,6,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
6,7,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
7,8,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
8,1,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
9,2,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00

In [14]:
%%sql

SELECT
  customerkey,
  COUNT(*) AS total_orders,
  ROW_NUMBER() OVER(ORDER BY COUNT(*) DESC) AS rn,
  RANK() OVER(ORDER BY COUNT(*) DESC) AS rank,
  DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS dense_rank
FROM sales
GROUP BY customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey  total_orders     rn   rank  dense_rank
0          1834524            31      1      1           1
1          1375597            30      2      2           2
2           249557            27      3      3           3
3           459519            26      4      4           4
4          1495941            26      5      4           4
...            ...           ...    ...    ...         ...
49482      1448235             1  49483  39985          28
49483        89802             1  49484  39985          28
49484       675412             1  49485  39985          28
49485       638307             1  49486  39985          28
49486       618309             1  49487  39985          28

[49487 rows x 5 columns]

In [26]:
%%sql
/*
Rank stores based on the total number of orders they received. This will help identify the highest-performing store locations by order volume.

Start by joining the sales and store tables to associate each order with a storecode.
Use a CTE to count the total number of orders per store.
In the final query, apply three ranking functions (ROW_NUMBER(), RANK(), DENSE_RANK()) to rank stores based on their total order volume.
*/

WITH store_orders AS (
  SELECT
  storecode,
  COUNT(s.orderkey) AS order_count
FROM store st
JOIN sales s ON st.storekey = s.storekey
GROUP BY storecode
)
SELECT
  storecode,
  order_count,
  RANK() OVER(ORDER BY order_count DESC) AS rank,
  ROW_NUMBER() OVER(ORDER BY order_count DESC) AS rn,
  DENSE_RANK() OVER(ORDER BY order_count DESC) AS dense_rank
FROM store_orders

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

67 rows affected.

    storecode  order_count  rank  rn  dense_rank
0          -1        78305     1   1           1
1          54         3397     2   2           2
2          61         3334     3   3           3
3          45         3257     4   4           4
4          44         3255     5   5           5
..        ...          ...   ...  ..         ...
62         28          271    63  63          62
63          2           59    64  64          63
64         52           51    65  65          64
65         11           29    66  66          65
66         35           14    67  67          66

[67 rows x 5 columns]

In [31]:
%%sql
/*
Identify which customers have made a recent purchase within the last year of available data.
This helps distinguish active vs. inactive customers based on their most recent order.

Use a CTE to find the latest orderdate for each customerkey by applying ROW_NUMBER() in a window function and giving alias rn.
In the main query, use a CASE statement to label each customer as:
'Recent Purchase' if their last order was within one year of the most recent order in the dataset
'No Recent Purchase' otherwise
Filter to only keep the most recent order per customer using WHERE rn = 1.
*/

WITH last_orders AS (
  SELECT
    customerkey,
    orderdate,
    ROW_NUMBER() OVER(PARTITION BY customerkey ORDER BY orderdate DESC) AS rn
  FROM sales
)
SELECT
  lo.customerkey,
  lo.orderdate,
  (SELECT MAX(orderdate) FROM sales) AS latest_orderdate,
  CASE
    WHEN ((SELECT MAX(orderdate) FROM sales) - INTERVAL '1 year') <= lo.orderdate THEN 'Recent Purchase'
    ELSE 'No Recent Purchase'
  END AS activity
FROM last_orders lo
WHERE rn = 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey   orderdate latest_orderdate            activity
0               15  2021-03-08       2024-04-20  No Recent Purchase
1              180  2023-08-28       2024-04-20     Recent Purchase
2              185  2019-06-01       2024-04-20  No Recent Purchase
3              243  2016-05-19       2024-04-20  No Recent Purchase
4              387  2023-11-16       2024-04-20     Recent Purchase
...            ...         ...              ...                 ...
49482      2099619  2020-07-10       2024-04-20  No Recent Purchase
49483      2099656  2024-02-06       2024-04-20     Recent Purchase
49484      2099697  2022-09-13       2024-04-20  No Recent Purchase
49485      2099711  2017-08-14       2024-04-20  No Recent Purchase
49486      2099743  2023-02-11       2024-04-20  No Recent Purchase

[49487 rows x 4 columns]

In [37]:
%%sql

/*
Determine which customer cohorts (by year of first purchase) have the highest average lifetime value (LTV).
This helps identify which acquisition years brought in the most valuable customers.

Use a CTE to assign each customer a cohort year based on the year of their first order.
Calculate each customer's lifetime value by summing their total revenue.
In the final query, compute the average LTV per cohort year and rank cohorts using DENSE_RANK() based on average LTV.
*/

WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
    SUM(quantity * netprice * exchangerate) AS ltv
  FROM sales
  GROUP BY customerkey
)
SELECT
  cohort_year,
  AVG(ltv) AS avg_ltv,
  DENSE_RANK() OVER(ORDER BY AVG(ltv) DESC) AS ltv_rank
FROM yearly_cohort
GROUP BY cohort_year;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year  avg_ltv  ltv_rank
0        2016  5404.92         1
1        2017  5403.08         2
2        2015  5271.59         3
3        2018  4896.64         4
4        2019  4731.95         5
5        2021  3943.33         6
6        2020  3933.32         7
7        2022  3315.52         8
8        2023  2543.18         9
9        2024  2037.55        10

In [53]:
%%sql
/*
Track how customer purchasing behavior changes over time by assigning each customer to a cohort year (based on the year of their first purchase),
and then analyzing order activity on a monthly basis.

First, use a CTE to calculate the cohort year for each customer using the earliest orderdate.
Then in another CTE, aggregate the data by cohort year and order month to get:
The total number of unique orders (orderkey)
The total number of unique customers (customerkey)
Finally, apply ROW_NUMBER(), RANK(), and DENSE_RANK() to identify which cohort-month combinations had the highest order activity.
*/

WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year
  FROM sales
  GROUP BY customerkey
),
monthly_totals AS (
  SELECT
    yc.cohort_year,
    DATE_TRUNC('month', s.orderdate) AS order_month,
    COUNT(DISTINCT s.orderkey) AS unique_orders,
    COUNT(DISTINCT s.customerkey) AS unique_customers
  FROM sales s
  LEFT JOIN yearly_cohort yc ON s.customerkey = yc.customerkey
  GROUP BY yc.cohort_year, order_month
)
SELECT
  cohort_year,
  order_month,
  unique_orders,
  unique_customers,
  RANK() OVER(ORDER BY unique_orders DESC) AS rank,
  DENSE_RANK() OVER(ORDER BY unique_orders DESC) AS dense,
  ROW_NUMBER() OVER(ORDER BY unique_orders DESC) AS rn
FROM monthly_totals

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

580 rows affected.

,cohort_year,order_month,unique_orders,unique_customers,rank,dense,rn
0,2022,2022-12-01 00:00:00+00:00,1083,1066,1,1,1
1,2019,2019-02-01 00:00:00+00:00,1019,1003,2,2,2
2,2018,2018-12-01 00:00:00+00:00,998,991,3,3,3
3,2022,2022-02-01 00:00:00+00:00,991,985,4,4,4
4,2022,2022-06-01 00:00:00+00:00,969,952,5,5,5
...,...,...,...,...,...,...,...
575,2015,2020-11-01 00:00:00+00:00,5,5,575,249,576
576,2016,2020-10-01 00:00:00+00:00,4,4,577,250,577
577,2015,2017-04-01 00:00:00+00:00,4,4,577,250,578
578,2015,2020-09-01 00:00:00+00:00,2,2,579,251,579
579,2015,2016-04-01 00:00:00+00:00,1,1,580,252,580

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql